<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.SqlClient" Version="6.1.3" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\integrations\sqlserver\src\Workable.SqlServer\Workable.SqlServer.csproj" />
    <ProjectReference Include="..\Workable\Workable.csproj" />
    <ProjectReference Include="..\Workable.Views\Workable.Views.csproj" />
  </ItemGroup>

</Project>
